# Generated by Django 5.0.4 on 2024-04-28 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aral_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ourpartnersmodel',
            name='url',
            field=models.URLField(default='https://araltech.tech/'),
        ),
    ]
